### ISSUE TITLE
HTML Form generation

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer-concerto#10]
It would be lovely to have a code generator that generates an HTML form from a modelled type. The form should generate valid JSON for the type so that it can be used to create or update instances.

There is the start of such a thing here:
https://github.com/uchibeke/composer-form

**Comment by mttrbrts** [comment]
The latest work is available in a fork of Uchi's work here, https://github.com/mttrbrts/concerto-form

Eventually, I see this ending up in https://github.com/hyperledger/composer-concerto-tools
