### ISSUE TITLE
Implicit super types specification

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer-concerto#11]
We allow the `ModelManager` to specify implicit super types for class declarations (currently via a map).  The map based approach has a couple of issues:
1. It doesn't work well when multiple system namespaces have been added as the return value is a type name without a namespace
2. It is not clear whether we should only allow implicit super types when there is no explicit super type
3. Should we allow implicit super types for types that are not defined in a system model file?

This is also related to the `ClassDeclaration.isSystemCoreType` method.

**Comment by dselman** [comment]
One approach would be for `ClassDeclaration.getSuperType` to delegate to its `ModelManager`. This would allow sub-classes of `ModelManager` to override the `ClassDeclarations` explicit super type based on decorators, namespace, maps etc.

**Comment by jeromesimeon** [comment]
What's the use case for implicit super types? The only example I have in mind is when you write `e.g., asset Foo { ... }` there is an implicit `Asset` super type.
