### ISSUE TITLE
cannot find module error

### ISSUE THREAD

**Issue by j4m3sb0mb** [hyperledger/composer-concerto#43]
When I use composer-concerto into another package  and then I use this new package into an application it throws this error:
`Error: Cannot find module 'doctrine'`

## Context
doctrine and acorn are required by the application but have been moved in devDependencies

## Expected Behavior
no errors

## Actual Behavior
this error:
`Error: Cannot find module 'doctrine'`

## Possible Fix
move doctrine and acorn to dependencies

## Steps to Reproduce
1. use composer-concerto in a module
2. import the module into an application
3. run the application

## Context
import composer-concerto in another package

## Your Environment
* Version used: 0.71.3
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js v11.10.1
* Operating System and version (desktop or mobile): Fedora Linux
* Link to your project:

**Comment by jeromesimeon** [comment]
It think this is a dependency issue. I believe `doctrine` and `acorn` should be in the `dependencies` category rather than the `devDependencies` part of the `package.json`.

**Comment by jeromesimeon** [comment]
For some reason there has been a bit of ping pong on those:

https://github.com/hyperledger/composer-concerto/commit/67b7150bcee9c8c1e1c5f4005ab019c425810fa1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

https://github.com/hyperledger/composer-concerto/commit/533b80f1e28be57de7a2806ee827ecab58a98536

And a PR to put those back to `dependencies` is at #44

**Comment by j4m3sb0mb** [comment]
thank you
